# -*- coding: utf-8 -*-
"""Emapthica2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TUPhVBYGqb-z2QAiYa5LeVKqCrdyf2zY
"""

import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from transformers import BertTokenizer, BertModel
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import Dataset, DataLoader

df = pd.read_csv("/content/counsel_chat.csv")

df = df[['questionText','answerText','therapistInfo','topic']]
df = df.dropna()

print(df.head())

le = LabelEncoder()
df['label'] = le.fit_transform(df['topic'])

train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['questionText'],
    df['label'],
    test_size=0.2,
    random_state=42
)

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

class ChatDataset(Dataset):

    def __init__(self, texts, labels):
        self.texts = texts.tolist()
        self.labels = labels.tolist()

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):

        encoding = tokenizer(
            self.texts[idx],
            padding='max_length',
            truncation=True,
            max_length=128,
            return_tensors='pt'
        )

        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'label': torch.tensor(self.labels[idx], dtype=torch.long)
        }

train_dataset = ChatDataset(train_texts, train_labels)
val_dataset = ChatDataset(val_texts, val_labels)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)

class NBERT(nn.Module):

    def __init__(self, num_classes):
        super(NBERT, self).__init__()

        self.bert = BertModel.from_pretrained('bert-base-uncased')

        self.lstm = nn.LSTM(
            input_size=768,
            hidden_size=128,
            batch_first=True,
            bidirectional=True
        )

        self.attention = nn.Linear(256,1)

        self.fc = nn.Linear(256,num_classes)
        self.dropout = nn.Dropout(0.3)

    def forward(self,input_ids,attention_mask):

        outputs = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        sequence_output = outputs.last_hidden_state

        lstm_out,_ = self.lstm(sequence_output)

        attn_weights = torch.softmax(self.attention(lstm_out),dim=1)

        context = torch.sum(attn_weights * lstm_out,dim=1)

        out = self.dropout(context)

        return self.fc(out)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = NBERT(num_classes=len(le.classes_)).to(device)

optimizer = torch.optim.AdamW(model.parameters(),lr=2e-5)

criterion = nn.CrossEntropyLoss()

EPOCHS = 3

for epoch in range(EPOCHS):

    model.train()
    total_loss = 0

    for batch in train_loader:

        optimizer.zero_grad()

        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        outputs = model(input_ids,attention_mask)

        loss = criterion(outputs,labels)

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

    print("Epoch:",epoch+1,"Loss:",total_loss/len(train_loader))

def predict_emotion(text):

    model.eval()

    encoding = tokenizer(
        text,
        padding='max_length',
        truncation=True,
        max_length=128,
        return_tensors='pt'
    )

    input_ids = encoding['input_ids'].to(device)
    attention_mask = encoding['attention_mask'].to(device)

    with torch.no_grad():

        outputs = model(input_ids,attention_mask)

    pred = torch.argmax(outputs,dim=1).cpu().item()

    return le.inverse_transform([pred])[0]

from sentence_transformers import SentenceTransformer, util

sbert = SentenceTransformer('all-MiniLM-L6-v2')

questions = df['questionText'].tolist()
answers = df['answerText'].tolist()
therapists = df['therapistInfo'].tolist()
topics = df['topic'].tolist()

question_embeddings = sbert.encode(questions,convert_to_tensor=True)

def chatbot_response(user_input):

    emotion = predict_emotion(user_input)

    user_embedding = sbert.encode(user_input,convert_to_tensor=True)

    scores = util.cos_sim(user_embedding,question_embeddings)

    best_match = torch.argmax(scores).item()

    response = answers[best_match]
    therapist = therapists[best_match]
    topic = topics[best_match]

    return f"""
Detected Emotion: {emotion}

Topic: {topic}

Therapist Info:
{therapist}

Therapist Advice:
{response}
"""

print(chatbot_response("I feel very lonely and nobody understands me"))

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def super_fast_accuracy(df, question_embeddings):

    print("Starting...", flush=True)

    emb_matrix = np.array([emb.cpu().numpy().flatten() for emb in question_embeddings])

    print("Embeddings ready", flush=True)


    sim_matrix = cosine_similarity(emb_matrix)

    print("Similarity computed", flush=True)


    np.fill_diagonal(sim_matrix, -1)


    best_matches = np.argmax(sim_matrix, axis=1)


    topics = df['topic'].values

    correct = np.sum(topics == topics[best_matches])
    total = len(df)

    accuracy = correct / total

    print("FINAL ACCURACY:", accuracy, flush=True)

    return accuracy


super_fast_accuracy(df, question_embeddings)